config-version: 2

name: 'mixpanel'
version: '0.0.1'

require-dbt-version: '>=0.17.0'

models:
    mixpanel:
        materialized: table 


vars: # todo: move these to the readme due to [order of variable declaration precedence](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-variables/#variable-precedence) 
    mixpanel: 
        event_table: "{{ source('mixpanel', 'src_mixpanel_dupe_events') }}"  # switch table to 'event' before releasing
        custom_event_columns: [ 'ios_ifa' ]
        has_android_events: true
        has_ios_events: true
        has_web_events: true
        # date_range_days: 180 
        
        
profile: dev_bigquery_dbt_testing