config-version: 2

name: 'mixpanel'
version: '0.0.1'

require-dbt-version: '>=0.18.0'


vars: # todo: move these to the readme due to [order of variable declaration precedence](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-variables/#variable-precedence) 
    mixpanel: 
        event_table: "{{ source('mixpanel', 'sample_mixpanel_events') }}"  # switch table to 'event' before releasing

        # date_range_start: '2020-09-01' 

        event_custom_columns: [ 'ios_ifa' ]
        event_properties_to_pivot: ['user_id', 'video_id', 'videoId']

        timeline_criteria: "coalesce(country_code, '') = 'US'"

        session_passthrough_columns: ['city', 'referrer', 'search_engine']
        
        
profile: dev_bigquery_dbt_testing
# integration_test